<?php
/** @var Custom_View $this */

/** @var Model_Topic_Entity $topicEntity */
$topicEntity = $this->topicEntity;
?>



<div class="topicList">
    <div class="media">
        <span class="pull-left">
            <img class="media-object" data-src="holder.js/64x64">
        </span>

        <div class="media-body">
            <p><?php echo nl2br($topicEntity->text) ?></p>
        </div>
    </div>
</div>