<?php
/** @var Custom_View $this */

/** @var Model_Topic_Entity[] $topicList */
$topicList = $this->topicList;
?>
<p class="lead">
    <a class="btn btn-primary " href="<?php echo $this->url(array('controller' => $this->currentController(), 'action' => 'add'), 'default', true) ?>">Add
        topic</a>
</p>

<section class="topicList">
    <?php foreach ($topicList as $topicEntity): ?>
        <?php $topicUrl = $this->url(array('controller' => $this->currentController(), 'action' => 'item', 'id' => $topicEntity->id), 'default', true) ?>

        <div class="media <?php echo $topicEntity->isDeleted ? 'well well-small' : '' ?>">
            <a class="pull-left" href="<?php echo $topicUrl ?>">
                <img class="media-object" data-src="holder.js/64x64">
            </a>

            <div class="media-body">
                <h4 class="media-heading controls">
                    <a href="<?php echo $topicUrl ?>">
                        <?php echo $this->escape($topicEntity->title) ?>
                    </a>
                    <small>
                    <?php $editUrl = $this->url(
                        array(
                            'controller' => $this->currentController(), 
                            'action' => 'edit', 
                            'id' => $topicEntity->id
                        ), 'default', true
                    ) ?>                    
                        <a href="<?php echo $editUrl ?>">Edit</a>                    
                    </small>
                        <?php $deleteUrl = $this->url(
                            array(
                                'controller' => $this->currentController(), 
                                'action' => $topicEntity->isDeleted ? 'restore' : 'delete', 
                                'id' => $topicEntity->id
                            ), 'default', true
                        ) ?>
                        <form action="<?php echo $deleteUrl ?>" class="pull-right" method="post">
                            <?php echo $this->formSubmit(
                                null,
                                $topicEntity->isDeleted ? 'restore' : 'delete',
                                array(
                                    'class' => 'btn btn-small'
                                )
                            ) ?>
                        </form>
                </h4>
                <h5>
                    <em>
                        <?php $date = new Zend_Date($topicEntity->timestampAdd);
                        echo $date->toString(Zend_Date::DATETIME_MEDIUM) ?>
                        by <a href="<?php echo $this->url(
                            array('module' => $this->currentModule(), 'controller' => 'user', 'action' => 'item', 'id' => $topicEntity->user->id), 'default',
                            true
                        ) ?>">
                            <?php echo $this->escape($topicEntity->user->name) ?>
                        </a>
                    </em>
                </h5>

                <p><?php echo nl2br(mb_strimwidth($topicEntity->text, 0, 200, "... <a href=\"$topicUrl\">Read more</a>")) ?></p>
            </div>
        </div>

    <?php endforeach ?>
</section>

