<?php
/** @var Custom_View $this */

$this->headMeta("width=device-width, initial-scale=1.0", 'viewport');
//    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

$this->headLink()->prependStylesheet('/css/font-awesome.css', array('media' => 'screen,print'));
$this->headLink()->prependStylesheet('/css/bootstrap-responsive.css', array('media' => 'screen,print'));
$this->headLink()->prependStylesheet('/css/bootstrap.css', array('media' => 'screen,print'));
$this->headLink()->prependStylesheet('/css/styles.css', array('media' => 'screen,print'));

$this->headScript()->appendScript(
    "var require = {
        appDir: '.',
        baseUrl: '/js',
        paths: {
            underscore: 'vendor/underscore',
            async: 'vendor/async',
            dom: ['vendor/jquery', '//code.jquery.com/jquery-1.9.1.min.js'],
            bootstrap: ['vendor/bootstrap', '//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js']
        },
        shim: {
            async: {
                exports: 'async'
            },
            underscore: {
                exports: '_'
            },
            dom: {
                exports: 'jQuery'
            },
            bootstrap: ['dom']
        },
        deps: ['vendor/json2', 'bootstrap', 'app']
    };"
);

$this->headScript()->appendFile('/js/vendor/require.js', 'text/javascript');

$this->headStyle()->appendStyle(
    'body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
    }'
);

$headTitle = $this->headTitle()->getValue();
if (!is_array($headTitle)) {
    $headTitle = array($headTitle);
}
if ($this->headTitle()->getDefaultAttachOrder() === Zend_View_Helper_Placeholder_Container_Abstract::APPEND) {
    $title = array_shift($headTitle);
    $subTitle = array_shift($headTitle);
} else {
    $title = array_pop($headTitle);
    $subTitle = array_pop($headTitle);
}
?>

<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
</head>


<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="<?php echo $this->url(array(), 'default', true) ?>">Blog</a>

            <div class="nav-collapse collapse">
                <?php echo $this->navigation()->menu()->renderMenu(null, array('maxDepth' => 0, 'ulClass' => 'nav', 'expandSiblingNodesOfActiveBranch' => 1)); ?>
            </div>
        </div>
    </div>
</div>

<div class="container">


    <?php
    /** @var Zend_Controller_Action_Helper_FlashMessenger $flashMessenger */
    $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
    ?>
    <?php if ($flashMessenger->hasCurrentMessages()): ?>
        <blockquote>
            <?php foreach ($flashMessenger->getCurrentMessages() as $message): ?>
                <?php echo $message ?>
            <?php endforeach ?>
        </blockquote>
    <?php endif ?>

    <div class="page-header">
        <h1>
            <?php echo $this->escape($title) ?>
            <small><?php echo $this->escape($subTitle) ?></small>
        </h1>
    </div>

    <?php echo $this->layout()->content ?>
</div>

</body>

</html>