<?php
/** @var Custom_View $this */

/** @var Model_Topic_Entity $userEntity */
$userEntity = $this->userEntity;
?>

<div class="userList">
    <div class="media">
        <span class="pull-left">
            <img class="media-object" data-src="holder.js/64x64">
        </span>

        <div class="media-body">
            <h5 class="media-heading">
                <a href="<?php echo $userUrl ?>">
                    <?php echo $this->escape($userEntity->email) ?>
                </a>
            </h5>
            <p>Joined: <?php $date = new Zend_Date($userEntity->timestampAdd); echo $date->toString(Zend_Date::DATETIME_MEDIUM) ?></p>
        </div>


    </div>
</div>