<?php
/** @var Custom_View $this */

/** @var Model_Topic_Entity $userEntity */
$userEntity = $this->userEntity;
?>

<div class="userList">
    <div class="media">
        <span class="pull-left">
            <img class="media-object" data-src="holder.js/64x64">
        </span>

        <div class="media-body">
            <h5 class="media-heading">
                <a href="<?php echo $this->url(array('module' => $this->currentModule(), 'controller' => 'user', 'action' => 'item', 'id' => $userEntity->id), 'default', true) ?>">
                    <?php echo $this->escape($userEntity->email) ?>
                </a>
            </h5>

            <p>Joined: <?php $date = new Zend_Date($userEntity->timestampAdd);
                echo $date->toString(Zend_Date::DATETIME_MEDIUM) ?></p>
            
            <p>Comments: <em><?php echo $this->escape($userEntity->countComment) ?></em></p>
            <p>Topics: <em><?php echo $this->escape($userEntity->countTopic) ?></em></p>
         </div>


    </div>
</div>

<h3>User's comments:</h3>

<div class="well">
    <?php echo $this->partial('comment/index.phtml', array(
        'commentList' => $userEntity->commentList
    )) ?>
</div>